name: golf_pro_app
description: A premium Golf Training and Tools application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/driving_range.jpg
    - assets/golf_course.jpg
    - assets/golf_course2.jpg
    - assets/golf_grip.jpg
    - assets/putting_green.jpg
    - assets/bunker_sand.jpg
    - assets/bunker_shot.jpg